J3RN/time-tracker

Gemfile
Gemfile.lock
app/models/tag.rb
app/models/task.rb
app/models/user.rb
db/migrate/20160304002440_remove_orphans.rb
db/schema.rb
test/models/tag_test.rb
test/models/task_test.rb
test/models/user_test.rb
test/test_helper.rb

Now `Tagging`s are destroyed alongside their tags or tasks. `TimeEntry`s are destroyed alongside their tasks.

dependent: :destroy relations

---

app/views/time_entries/_form.html.erb

Until now, the form has always said "Create", even when you are editing. This rectifies that.

Fixed wording in TE form

---

app/controllers/tasks_controller.rb
db/seeds.rb
test/controllers/tasks_controller_test.rb
test/fixtures/tasks.yml

The answer was to do `reorder` instead of `unscoped`.
Fixes #22

View other user's tasks bugfix

---

app/helpers/time_entries_helper.rb

For the duration display helper methods, the time would be shown in minutes if
it was exactly 60 minutes, and I would prefer for it to be shown as "1 hour"

Super minor >= 60 fix

---

app/models/task.rb

This is useful when trying to decide between tasks due on the same day
and of the same priority. My preference would be to do the longest one
first.

Sort by estimate after due date and priority

---

app/views/tags/_form.html.erb
app/views/tasks/_form.html.erb
app/views/time_entries/_form.html.erb

This is a nifty feature, because you otherwise have to click on it or
tab to it or something.

Autofocus first field on all forms

---

app/views/time_entries/index.html.erb

Currently, you have to confirm deleting Tasks and Tags, but no such
protection was in place for deleting Time Entries. This bit me a couple
of times, so I'm adding in that protection measure.

Confirm deleting Time Entries

---

app/assets/javascripts/tasks.js

The event listener was not being reloaded on page changes (thanks,
Turbolinks!). The event listener load call has now been moved to the
"page:change" event callback with the other event listener loads.
Closes #38

Fix for the archive toggle

---

Gemfile
Gemfile.lock

I moved passenger and dotenv into the 'production' group so they won't
be installed in CI. I also removed the babel dependence because it
wasn't used.

Dependency update

---

app/assets/javascripts/tasks.js
app/assets/javascripts/time_entries.js
app/controllers/tasks_controller.rb
app/views/tasks/_form.html.erb
app/views/time_entries/_form.html.erb
config/initializers/monkey_patching.rb
lib/core_extensions/date/custom_formats.rb
test/controllers/tasks_controller_test.rb

Since the introduction of due dates, the JavaScript has always set the due date
to be the current day's date, even if you are editing an older task whose due
date is far in the future. This PR makes it so that dates will not be
overridden and uses the pretty date picker pulled in for Time Entry start times.
UPDATED 2016-08-27 to reflect new approach.

Fixed due date bug on update

---

app/models/task.rb

Task names should not need to be unique. Unsure what I was thinking when I wrote that.

Task name uniqueness bugfix

---

app/assets/stylesheets/styles.scss
app/models/task.rb
app/views/tasks/_task_table.html.erb

Hi @J3RN!  :wave:
I had a few minutes today to participate in Hacktoberfest, and I came across #46 where you mentioned wanting overdue items to visually stand out.
This Pull Request adds some simple line highlighting to overdue rows in the task table.  An overdue item's row receives a lighter version of it's corresponding priority swatch.
I did end up changing the color for priority 1 to gray, but I also refactored the styles a bit to make future color maintenance a bit easier.
If you have some time to play around with this, let me know what you think!  I'm happy to make changes, but feel free to :hammer: around on this branch too! :smiley:

Overdue task style

---

app/models/task.rb
test/models/task_test.rb

Long story short, `Date#to_time` evidently works better for database queries. It seems that just using a Date didn't account for timezones, but switching it to a Time did.

Timezone "Time due today" fix

---

app/helpers/application_helper.rb
app/views/tasks/_task_table.html.erb
app/views/time_entries/index.html.erb
app/views/time_entries/report.html.erb

feat: Using a single short duration display format

---

app/assets/stylesheets/styles.scss
app/views/tasks/_form.html.erb

When I first started using this I didn't know which way priorities went (is a #1 priority the highest or lowest?). These tooltips should avoid such confusion, and allow tooltips to easily be copied over to other pages if that's desired later on

Added tooltips for task creation

---

README.md

Current behaviour:
> git clone git@github.com:J3RN/timesheet.git
Cloning into 'timesheet'...
Permission denied (publickey).
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.

Gitlink in README.md

---

app/models/task.rb
test/models/task_test.rb

What it says on the tin.
Task list at the beginning of the day:
Task list after having logged some time:
Notice that Task 123 did not drop below Task 456 despite it now having less time remaining. This new behavior encourages users to work on a task until their daily time for it is completed first, then move on to another.
A consequence of this was that `due_today` had to become a public method, and is now tested as such.

`order_todo` uses `due_today` instead of `time_remaining_today`

---

Gemfile
Gemfile.lock
README.md
test/test_helper.rb

Fix [#85](https://github.com/J3RN/timesheet/issues/85)
Adds SimpleCov as a test coverage solution. After running tests, coverage report is available under `coverage/index.html` as shown below.

Adds test coverage gem SimpleCov

---

app/controllers/time_entries_controller.rb
test/controllers/time_entries_controller_test.rb

Fix #56 
After a successful `time_entry` update, redirects you to `time_entires#index` for the `start_date` of the `time_entry`.
The `start_date` field gets hidden on `time_entries#new` (since it's blank) so I left that as-is.

Redirect to start_time day after successful time_entries#edit

---

app/views/layouts/application.html.erb

The 1, 2, and 3 keybindings for changing the page were conflicting with
Alt-1, Alt-2, and Alt-3 for changing tabs. I decided to make these more
semantic in addition to removing the conflict as well as adding two
additional keybindings. The new keybindings are as follows:
- t`A`gs
- ta`S`ks
- time `E`ntries
- `L`og in
- s`I`gn up
It was a conscious design decision that all of these are on or near the
home row, for additional comfort.
I would love a second pair of eyes on this to make sure I'm not crazy.

Semantic keybindings

---

app/assets/stylesheets/styles.scss
app/helpers/application_helper.rb
app/views/tasks/_archived_task_table.html.erb
app/views/tasks/_task_table.html.erb
app/views/time_entries/_time_entries.html.erb

On the Tasks#index page:
On TimeEntries#index:
Regrettably, `<option>` tags are not allowed to contain HTML, so they are still left looking the same:
I'm fairly satisfied with this, so unless anyone raises serious concerns within the next hour or so, I'll be merging this.
Closes #107

Added Tag labels for index views

---

app/assets/javascripts/tasks.js
app/controllers/tasks_controller.rb
app/models/task.rb
app/views/tasks/_form.html.erb
db/migrate/20161116200213_add_start_date_to_tasks.rb
db/schema.rb
test/controllers/tasks_controller_test.rb
test/controllers/time_entries_controller_test.rb
test/fixtures/tasks.yml
test/models/tag_test.rb
test/models/task_test.rb
test/models/user_test.rb

The motivation here is to have a way to add tasks that do not require immediate work (e.g. due in two weeks, estimate is 2 minutes / day). There are some interesting details about the implementation here that require scrutiny:
- Start dates are not required, but have a default (today)
- Said default exists only in the UI, but is not enforced by the database
Instead of changing the "New Task" screen, there is a button on the Tasks page labelled something like "Procrastinate." Pressing this button will set the start date to the subsequent day. This, despite it's name, should actually deincentivize procrastination, since procrastinating entails pushing the "Procrastinate" button every day.
I'd absolutely adore feedback :sparkles:
Closes #98

[WIP] Added start date to Tasks

---

db/schema.rb

When migrating `master`, this change cropped up. I assume it's a Rails 5 thing, and should be good to merge.

Schema index changes

---

app/assets/javascripts/time_entries.js

This script is only intended to be run on the TimeEntries#index page. Unfortunately, it runs on every page, which results in a lot of queries to the server with the GET parameter `date=undefined`. By checking that `filterDate` is truthy (i.e. not `undefined` or some other not-date things), we should be reasonably confident that the date being sent to the server is probably actually a date.

Stop polling if 'filterDate' is undefined

---

app/assets/javascripts/time_entries.js
app/assets/stylesheets/styles.scss
app/controllers/time_entries_controller.rb
app/models/time_entry.rb
app/views/time_entries/_entries_table.html.erb
app/views/time_entries/index.html.erb
app/views/time_entries/updates_all_time_entries.html.erb
app/views/time_entries/updates_all_time_entries.js.erb

People (myself included) sometimes forget to stop timers. When a day passes and these timers are forgotten, this can lead to things getting really messed up (like time remaining, percent of estimate done, etc). This PR will make it so that all running timers are included on every time entry page so that they will not be forgotten about.
This is a first pass, and is subject to change.
Closes #82

Show running time entries on today's page

---

app/models/task.rb
test/fixtures/time_entries.yml
test/models/task_test.rb
test/models/time_entry_test.rb

The coverage showed that there were two methods not sufficiently covered in all of the models: `TimeEntry#real_duration` and `TimeEntry.to_csv`. The latter proved quite difficult to test, and needs rewriting anyways. This PR adds a test for the former.
Fixes #3

TimeEntry tests

---

app/assets/javascripts/tasks.js
app/assets/stylesheets/styles.scss
app/controllers/tasks_controller.rb
app/models/task.rb
app/views/tasks/_completed_task_table.html.erb
app/views/tasks/_task_table.html.erb
app/views/tasks/index.html.erb
db/migrate/20180331020228_rename_archived_completed.rb
db/schema.rb
db/seeds.rb
test/controllers/tasks_controller_test.rb
test/controllers/time_entries_controller_test.rb
test/fixtures/tasks.yml
test/models/task_test.rb
test/models/user_test.rb

Which is funny, in retrospect, because org-mode (now a major influence
on development) uses the term "archived" instead of "completed." In
any event, this was a massive find-and-replace operation. I'll be
lucky if nothing major breaks.
Fixes #115

Rename archived to completed

---

app/assets/javascripts/tasks.js
app/assets/stylesheets/styles.scss
app/controllers/tasks_controller.rb
app/helpers/tasks_helper.rb
app/views/tasks/index.html.erb
config/routes.rb

Evidently, in the previous PR, I missed instances of "archive" in
favor of instances of "archived."

Rename "archive" to "complete"

---

config/initializers/sentry.rb

There's a caveat here wherein I assume that `config/initializers/filter_parameter_logging.rb` is loaded before this file as it modifies `Rails.application.config.filter_parameters`. I suppose if the load order ever changes, I'll have to move this Raven configuration into `config/application.rb` or somewhere like that.

Send POST data and cookies with Sentry

---

app/models/user.rb
config/environments/production.rb
config/environments/staging.rb
config/initializers/devise.rb
db/migrate/20180331033131_add_confirmable_to_users.rb
db/schema.rb
test/fixtures/users.yml

Taking a look through the database, I noticed that some people signed
up with junk email addresses. I'd like to put a stop to that.
I loosely followed [the :confirmable guide on the Devise wiki](https://github.com/plataformatec/devise/wiki/How-To:-Add-:confirmable-to-Users).
Fixes #119

Make users confirm their email addresses

---

app/helpers/application_helper.rb
test/helpers/application_helper_test.rb

Instead of displaying a string like "1 hour and 0 minutes", just display "1 hour"

Shorten long duration string if no minutes

---

Gemfile.lock

Apparently loofah had a vulnerability, so it was updated. That update pulled in a more recent (but, according to semantic versioning) compatible nokogiri. Running the passenger server also created a security warning, so that was updated as well.

Update gems to fix vulernabilities

---

db/seeds.rb

The seeds, as they were, didn't account for the fact that Time Tracker now requires that you confirm your email address. This update sets the `confirmed_at` fields for the user seed records.

Update seeds to fix login issue
