- app/controllers/time_entries_controller.rb
- test/controllers/time_entries_controller_test.rb
Added a test for ensuring that the user can view their own reports, and not view other users' reports
> Ensure ownership over reports

- .gitignore
- Gemfile
- Gemfile.lock
- Updated the gitignore to exclude (Vagrant stuff & logs)
- Added 'therubyracer' to the gemfile
> Working Vagrant setup additions

- app/models/task.rb
- db/seeds.rb
This is a similar method to that used by Todoist, pictured here:
While my implementation is less aesthetically pleasing, it does the same this. Picture:
@3ygun @jmkuehn Thoughts?
> Sort by due date first

- app/helpers/application_helper.rb
- app/views/time_entries/report.html.erb
Also a new standard date format
> Reports show time entry dates

- app/assets/javascripts/tasks.js
- app/assets/stylesheets/styles.scss
- app/views/tasks/index.html.erb
My solution was to add a link and watch it's click action with jQuery. When
clicked, it uses a variable to determine the state of the hidden section, takes
the appropriate action (hide/show), updates the link to have appropriate text,
and the updates the variable.
> Toggle Archived

- app/assets/javascripts/application.js
- app/views/layouts/application.html.erb
As described, with the side effect of also including Bootstrap's neglected javascript component.
> Toggleable mobile navbar

- app/assets/javascripts/tasks.js
- app/views/tasks/_task_table.html.erb
> Added checkboxes for "completion"

- app/assets/javascripts/time_entries.js
> Fix for running toggle bug

- Gemfile
- Gemfile.lock
- app/assets/javascripts/application.js
- app/assets/javascripts/time_entries.js
- app/assets/stylesheets/application.scss
- app/controllers/time_entries_controller.rb
- app/models/time_entry.rb
- app/views/time_entries/_form.html.erb
- config/application.rb
- config/initializers/monkey_patching.rb
- lib/core_extensions/time/custom_formats.rb
- test/controllers/time_entries_controller_test.rb
The idea is adding a time entry from a previous date, which I would currently
really like to do.
> Allow user to change start date of time entries

- app/controllers/tags_controller.rb
- app/controllers/tasks_controller.rb
- app/controllers/time_entries_controller.rb
- app/models/tag.rb
- app/models/task.rb
- app/views/tags/_form.html.erb
- app/views/tasks/_form.html.erb
- app/views/time_entries/_form.html.erb
- test/controllers/tags_controller_test.rb
- test/controllers/tasks_controller_test.rb
- test/controllers/time_entries_controller_test.rb
- test/fixtures/time_entries.yml
- test/fixtures/users.yml
> Added fail-to-save catches

- app/controllers/time_entries_controller.rb
> Update time entry with archived task fix

- app/controllers/time_entries_controller.rb
- db/migrate/20160829215454_default_duration_to_zero.rb
- db/schema.rb
> Default duration for time entries to 0

- app/models/task.rb
- test/fixtures/tasks.yml
- test/models/task_test.rb
There was a divide by zero issue
> Bugfix for zero days remaining

- app/models/task.rb
- test/models/task_test.rb
I added an explicit return of '0' if the value of `left_today` is negative.
I also did a slight refactor. I split `time_remaining_today` into three methods, two of which are small, private methods.
> Time remaining always positive

- app/models/task.rb
This implementation is inelegant, and I would appreciate it if anyone could suggest a better one.
> Order first by whether time is due today, then by priority

- app/assets/stylesheets/styles.scss
The buttons now work on a small screen.
> fixed buttons on small screen

- app/assets/javascripts/time_entries.js
- app/controllers/time_entries_controller.rb
- app/views/time_entries/_time_entries.html.erb
- app/views/time_entries/index.html.erb
- app/views/time_entries/updates_all_time_entries.js.erb
- config/routes.rb
- using ajax call to update time entries without an reload page
ref #75
> Improves the reload of the time entries with ajax

- README.md
Installing PostgreSQL in Ubuntu isn't the dumpster fire I remember it
being when I wrote this application. As such, I figured it's time to
remove my hostile comment.
> Removed condescending comment in README

- app/controllers/time_entries_controller.rb
Formerly, Time Entries would change order when refreshed via JavaScript
because they were not being ordered the same way in that function as in
the index function. I refactored it by adding a new method, which is a
before action for both of those methods.
> Fixed Time Entry reordering on refresh issue

- config/database.yml
I'm setting up a staging server, and this would be incredibly helpful
> Allow custom production database name

- app/controllers/time_entries_controller.rb
- app/models/task.rb
- app/models/time_entry.rb
- app/views/time_entries/_time_entries.html.erb
- app/views/time_entries/index.html.erb
- app/views/time_entries/updates_all_time_entries.js.erb
I was wanting the total durations to live update.
Thoughts, anyone?
> Account for running timers

- app/views/tasks/_archived_task_table.html.erb
- app/views/tasks/index.html.erb
> Added different table for archived

- app/assets/stylesheets/styles.scss
> Added bottom padding

- .travis.yml
- Gemfile
- Gemfile.lock
> Upgrade to 2.3.5

- Capfile
- config/deploy.rb
- config/environments/production.rb
- config/environments/staging.rb
Apparently *this* is why I keep that staging server around. Fixes mostly related to #124.
> Fixes for errors that wont let me deploy

- README.md
- bin/setup
- config/database.yml
> Revise setup script and instructions

- .travis.yml
I also cleaned up my messy, old Travis CI config.
> Add Coverage Reporting to Code Climate

- README.md
This probably should ahve been part of #135, but it didn't cross my mind at that point.
> Add Code Climate Coverage Badge

- .travis.yml
- Gemfile
- Gemfile.lock
- README.md
- config/deploy.rb
> Update to Ruby 2.5.1
